<ips:template parameters="$invoices" />

{template="pageHeader" group="global" app="core" params="\IPS\Member::loggedIn()->language()->get('orders_title')"}
<hr class='ipsHr'>

{{if count( $invoices )}}
	<ul class='ipsDataList ipsDataList_large cNexusOrderList'>
	{{foreach $invoices as $invoice}}
		<li class='ipsDataItem'>
			<div class='ipsDataItem_generic ipsDataItem_size8 ipsPos_top'>
				<strong class='ipsType_large'>{datetime="$invoice->date"}</strong><br>
				<span class='ipsType_normal ipsType_light'>{lang="order_title"} #{$invoice->id}</span> &middot; <a href='{$invoice->url()}' title="{lang="orders_view_details_title"}">{lang="order_view_details"}</a>
				
				<p>
					<span class='cNexusOrderBadge cNexusOrderBadge_{lang="$invoice->status"}'>{lang="istatus_{$invoice->status}"}</span> <strong class='ipsType_large cNexusPrice ipsPos_middle'>{$invoice->total}</strong>
				</p>
			</div>
			<div class='ipsDataItem_main'>
				{{$summary = $invoice->summary();}}
				{{if count( $summary['items'] )}}
					<ul class='ipsDataList cNexusOrderList_items'>
						{{foreach $summary['items'] as $k => $item}}
							<li class='ipsDataItem'>
								<div class='ipsDataItem_icon'>
									{{if $image = $item->image()}}
										<img src="{$image}" class='ipsImage ipsThumb_tiny'>
									{{else}}
										<div class='ipsNoThumb ipsNoThumb_product ipsThumb_tiny'>&nbsp;</div>
									{{endif}}
								</div>
								<div class='ipsDataItem_main'>
									{{if $url = $item->url()}}
										<a href="{$url}" class='ipsType_blendLinks ipsDataItem_title'>{$item->name}</a>
									{{else}}
										<span class='ipsDataItem_title'>{$item->name}</span>
									{{endif}}
									<p class='ipsType_light ipsType_reset'>{lang="quantity"}: {$item->quantity}</p>
									<p class='ipsType_light ipsType_reset'>{lang="invoice_unit_price"}: {$item->price}</p>
								</div>
							</li>
						{{endforeach}}
					</ul>
				{{else}}
					<span class='ipsType_normal ipsType_light'>{lang="orders_no_items"}</span>
				{{endif}}
			</div>
			<div class='ipsDataItem_generic ipsDataItem_size8 ipsPos_top'>
				<ul class='ipsToolList ipsToolList_vertical'>
					{{if $invoice->status === $invoice::STATUS_PENDING}}
						<li>
							<a href='{$invoice->checkoutUrl()}' class='ipsButton ipsButton_primary ipsButton_verySmall ipsButton_fullWidth' title="{lang="order_pay_now_title"}">{lang="order_pay_now"}</a>
						</li>
						<li>
							<a href='{$invoice->url()->setQueryString( 'do', 'cancel' )->csrf()}' data-confirm class='ipsButton ipsButton_light ipsButton_verySmall ipsButton_fullWidth' title="{lang="orders_cancel_title"}">{lang="orders_cancel"}</a>
						</li>
					{{endif}}

				</ul>
			</div>
		</li>
	{{endforeach}}
{{else}}
	<div class='ipsBox ipsPad ipsType_large ipsType_light ipsType_center'>
		{lang="orders_none"}
	</div>
{{endif}}