<ips:template parameters="$request" />

<h1 class='ipsType_pageTitle ipsSpacer_bottom ipsSpacer_half ipsFaded_withHover cNexusSupportRequest_title'>{$request->title} <a href='{$request->acpUrl()->setQueryString( 'do', 'editTitle' )}' class='ipsType_normal ipsFaded ipsFaded_more'>({lang="edit"})</a></h1>
<p class='ipsType_reset ipsType_normal'>
	{lang="request_created_ago" sprintf="\IPS\DateTime::formatInterval( \IPS\DateTime::ts( $request->mapped('date') )->diff( new \IPS\DateTime ), 2 )"}
	{{if $request->staff}}&nbsp;&nbsp;&nbsp;<strong class='ipsType_success'>{lang="assigned_to_x" sprintf="( $request->staff->member_id === \IPS\Member::loggedIn()->member_id ) ? \IPS\Member::loggedIn()->language()->addToStack('you') : $request->staff->name"}</strong>{{endif}}
</p>
<hr class='ipsHr'>
{{if isset( \IPS\Request::i()->pending ) and \IPS\Request::i()->pending}}
	<div class="ipsMessage ipsMessage_error ipsJS_hide" data-controller="nexus.admin.support.pendingalert">
		{lang="support_pending"}
	</div>
{{endif}}
{{$previous = $request->nextPrevious( \IPS\Request::i()->sort, \IPS\Request::i()->filter, TRUE );}}
{{$next = $request->nextPrevious( \IPS\Request::i()->sort, \IPS\Request::i()->filter );}}

{{if $previous || $next}}
	<nav class="ipsPager ipsPager_small ipsGrid ipsClearFix ipsList_inline">
		<div class="ipsGrid_span6 ipsPager_prev">
			{{if isset( \IPS\Request::i()->sort ) and $previous}}
				<a href="{$previous->acpUrl()->setQueryString( array( 'filter' => \IPS\Request::i()->filter, 'sort' => \IPS\Request::i()->sort ) )}" title="{lang="prev"}" rel="prev">
					<span class="ipsPager_type">{lang="prev_request"}</span>
					<span class="ipsPager_title ipsType_break">{wordbreak="$previous->title"}</span>
				</a>
			{{endif}}
		</div>
		<div class="ipsGrid_span6 ipsType_right ipsPager_next">
			{{if isset( \IPS\Request::i()->sort ) and $next}}
				<a href="{$next ->acpUrl()->setQueryString( array( 'filter' => \IPS\Request::i()->filter, 'sort' => \IPS\Request::i()->sort ) )}" title="{lang="next"}" rel="next">
					<span class="ipsPager_type">{lang="next_request"}</span>
					<span class="ipsPager_title ipsType_break">{wordbreak="$next->title"}</span>
				</a>
			{{endif}}
		</div>
	</nav>
	<br>
{{endif}}
<div class="ipsColumns ipsColumns_collapsePhone cNexusSupportRequest ipsSpacer_top">
	<div class='ipsColumn ipsColumn_fluid'>
		<h2 class='ipsType_sectionTitle ipsType_reset'>{lang="support_responses"}</h2>
		<section class='ipsBox'>
			<div data-controller='nexus.admin.support.replyArea' class='cNexusSupportForm ipsAreaBackground ipsPad'>
				<div class="ipsTabs ipsTabs_small ipsClearfix" id="elSupportForm" data-ipsTabBar data-ipsTabBar-contentArea="#elSupportForm_content">
					<a href="#elSupportForm" data-action="expandTabs"><i class="fa fa-caret-down"></i></a>
					<ul role="tablist">
						<li role="presentation">
							<a href="#" id="elStaffForm" class="ipsTabs_item ipsType_center ipsTabs_activeItem" data-role='replyTab' aria-selected="true">{lang="staff_reply"}</a>
						</li>
						<li role="presentation">
							<a href='#' id='elNoteForm' class='ipsTabs_item ipsType_center' data-role='noteTab'>{lang="staff_note"}</a>
						</li>
					</ul>
				</div>
				<div id="elSupportForm_content" class="ipsTabs_panels ipsTabs_contained ipsClearfix">
					<div id="ipsTabs_elSupportForm_elStaffForm_panel" class="ipsTabs_panel ipsAreaBackground_reset ipsClearfix" aria-hidden="false">
						{$request->staffReplyForm()|raw}
					</div>
					<div id="ipsTabs_elSupportForm_elNoteForm_panel" class="ipsTabs_panel ipsAreaBackground_reset ipsClearfix" aria-hidden="false">
						{$request->noteForm()|raw}
					</div>
				</div>			
			</div>
			<div class='ipsPad ipsAreaBackground_light' data-controller='core.front.core.commentFeed' data-baseURL='{$request->acpUrl()}' data-feedID='request-{$request->id}'>
				{{$order = isset( \IPS\Request::i()->order ) ? \IPS\Request::i()->order : ( isset( \IPS\Request::i()->cookie['support_order'] ) ? \IPS\Request::i()->cookie['support_order'] : 'desc' );}}
				<div class="ipsType_right ipsType_small">
					{{if $order === 'desc'}}
						<a href='{expression="\IPS\Request::i()->url()->setQueryString( array( 'order' => 'asc', 'page' => 1 ) )"}' class=''>{lang="responses_asc"}</a> &middot; {lang="responses_desc"}
					{{else}}
						{lang="responses_asc"} &middot; <a href='{expression="\IPS\Request::i()->url()->setQueryString( array( 'order' => 'desc', 'page' => 1 ) )"}' class=''>{lang="responses_desc"}</a>
					{{endif}}
				</div>
				<br>
				{{if $request->commentPageCount() > 1}}
					<div class='ipsSpacer_bottom'>
						{$request->commentPagination()|raw}
					</div>
				{{endif}}

				{{foreach $request->repliesAndLog( $order ) as $comment}}
					{{if $comment instanceof \IPS\nexus\Support\Reply}}
						{$comment->html()|raw}
					{{elseif $comment->new}}
						<p class='ipsType_reset ipsType_medium ipsSpacer_bottom cNexusSupportRequest_action'>
							{{if $comment->action === 'status'}}
								<i class='fa fa-cog'></i> &nbsp;&nbsp;{lang="reply_action_status" sprintf="$comment->member->name, $comment->new->_title"}
							{{elseif $comment->action === 'department'}}
								<i class='fa fa-exchange'></i> &nbsp;&nbsp;{lang="reply_action_moved" sprintf="$comment->member->name, $comment->new->_title"}
							{{elseif $comment->action === 'severity'}}
								<i class='fa fa-exclamation-triangle'></i> &nbsp;&nbsp;{lang="reply_action_severity" sprintf="$comment->member->name, $comment->new->_title"}
							{{elseif $comment->action === 'purchase'}}
								{{if $comment->new}}
									<i class='fa fa-cube'></i> &nbsp;&nbsp;{lang="reply_action_associate" sprintf="$comment->member->name" htmlsprintf="'<a href=\'{$comment->new->acpUrl()}\'>{$comment->new->name}</a>'"}
								{{else}}
									<i class='fa fa-minus-circle'></i> &nbsp;&nbsp;{lang="reply_action_unassociate" sprintf="$comment->member->name"}
								{{endif}}
							{{elseif $comment->action === 'staff'}}
								{{if $comment->new}}
									<i class='fa fa-user'></i> &nbsp;&nbsp;{lang="reply_action_assign" sprintf="$comment->member->name, $comment->new->name"}</a>
								{{else}}
									<i class='fa fa-minus-circle'></i> &nbsp;&nbsp;{lang="reply_action_unassign" sprintf="$comment->member->name"}
								{{endif}}
							{{endif}}

							<span class='ipsType_light cNexusAdminSupportMessage_date'>{datetime="$comment->date"}</span>
						</p>
					{{endif}}
				{{endforeach}}

				{{if $request->commentPageCount() > 1}}
					<div class='ipsSpacer_top'>
						{$request->commentPagination()|raw}
					</div>
				{{endif}}
			</div>
		</section>
	</div>
	<div class='ipsColumn ipsColumn_veryWide cNexusSupportRequest_metaInfo'>
		<h2 class='ipsType_sectionTitle ipsType_reset'>{lang="support_related"}</h2>
		<div class='ipsPad ipsAreaBackground'>
			<div class='ipsBox ipsSpacer_bottom'>
				<div class="ipsTabs ipsTabs_small ipsClearfix" id="elRequestMeta" data-ipsTabBar data-ipsTabBar-contentArea="#elRequestMeta_content">
					<a href="#elRequestMeta" data-action="expandTabs"><i class="fa fa-caret-down"></i></a>
					<ul role="tablist">
						<li role="presentation">
							<a href="#" id="elCustomerInfo" class="ipsTabs_item ipsType_center ipsTabs_activeItem" data-role='replyTab' aria-selected="true">{lang="support_info_customer"}</a>
						</li>
						{{if $otherRequests = $request->supportAuthor()->supportRequests( 10, $request ) and $otherRequests->count()}}
							<li role="presentation">
								<a href='#' id='elRequestHistory' class='ipsTabs_item ipsType_center' data-role='noteTab'>{lang="support_info_requests"}</a>
							</li>
						{{endif}}
						{{if member.hasAcpRestriction( 'nexus', 'payments', 'invoices_manage' ) and $invoices = $request->supportAuthor()->invoices()}}
							<li role="presentation">
								<a href='#' id='elInvoiceHistory' class='ipsTabs_item ipsType_center' data-role='noteTab'>{lang="support_info_invoices"}</a>
							</li>
						{{endif}}
					</ul>
				</div>
				<div id="elRequestMeta_content" class="ipsTabs_panels ipsTabs_contained ipsClearfix">
					<div id="ipsTabs_elRequestMeta_elCustomerInfo_panel" class="ipsTabs_panel ipsAreaBackground_reset ipsClearfix" aria-hidden="false">
						{{if $photo = $request->supportAuthor()->photo()}}
							<div class='ipsType_center'>
								{{if $link = $request->supportAuthor()->url()}}
									<a href="{$link}"><img src='{$photo}' class='ipsUserPhoto ipsUserPhoto_medium'></a>
								{{else}}
									<img src='{$photo}' class='ipsUserPhoto ipsUserPhoto_medium'>
								{{endif}}

								<p class='ipsType_reset'>
									<span class='ipsType_sectionHead'>
										{{if $name = $request->supportAuthor()->name()}}
											{{if $link = $request->supportAuthor()->url()}}
												<strong><a href="{$link}">{$name}</a></strong>
											{{else}}
												<strong>{$name}</strong>
											{{endif}}
										{{else}}
											<strong>{lang="request_member"}</strong>
										{{endif}}
									</span>
								</p>
								<hr class='ipsHr'>

								<ul class='ipsList_reset ipsType_medium'>
									{{foreach $request->supportAuthor()->meta() as $meta}}
										<li>{$meta}</li>
									{{endforeach}}
								</ul>
								
								{{if member.hasAcpRestriction( 'nexus', 'customers', 'customer_notes_view' ) and $request->member}}
									<hr class='ipsHr'>
									<p class='ipsType_reset ipsType_medium'>
										{{if $noteCount = $request->supportAuthor()->noteCount()}}
											<strong><a href='{url="app=nexus&module=customers&controller=view&id={$request->member}&view=notes&support={$request->id}"}' data-ipsDialog data-ipsDialog-title="{lang="customer_notes"}">{lang="num_customer_notes" pluralize="$noteCount"}</a></strong>
										{{else}}
											{lang="num_customer_notes" pluralize="0"}
										{{endif}}
										{{if member.hasAcpRestriction( 'nexus', 'customers', 'customer_notes_add' )}}
											&nbsp;&nbsp;<a href='{url="app=nexus&module=customers&controller=view&id={$request->member}&do=noteForm&support={$request->id}"}' data-ipsDialog data-ipsDialog-title="{lang="add_note"}">{lang="add_note"}</a>
										{{endif}}
									</p>
								{{endif}}

								{{if ( $request->member && \IPS\Member::loggedIn()->hasAcpRestriction( 'core', 'members', 'member_login' ) AND !\IPS\Member::load( $request->member )->isBanned() )}}
									<p class='ipsType_reset ipsType_medium'>
										<a href='{url="app=core&module=members&controller=members&do=login&id={$request->member}"}' target='_blank'>{lang="sign_in_as_customer"}</a>
									</p>
								{{endif}}
							</div>	
						{{endif}}
					</div>
					{{if $otherRequests}}
						<div id="ipsTabs_elRequestMeta_elRequestHistory_panel" class="ipsTabs_panel ipsAreaBackground_reset ipsClearfix" aria-hidden="false">
							<ul class='ipsDataList ipsDataList_reducedSpacing ipsList_reset'>
								{{foreach $otherRequests as $otherRequest}}
									<li class='ipsDataItem'>
										<div class='ipsDataItem_main'>
											{template="status" group="support" app="nexus" params="\IPS\nexus\Support\Status::load( $otherRequest->status->id ), 'ipsPos_right'"}
											<a href="{$otherRequest->acpUrl()}" data-ipsDialog data-ipsDialog-title="{$otherRequest->title} (#{$otherRequest->id})" data-ipsDialog-url="{$otherRequest->acpUrl()->setQueryString( 'popup', $request->id )}" class='ipsDataItem_title'>{$otherRequest->title}</a>
											<p class='ipsDataItem_meta ipsType_reset ipsType_small ipsType_light'>{datetime="$otherRequest->mapped('date')"}</p>
										</div>
									</li>
								{{endforeach}}
								{{if $otherRequests->count( TRUE ) > 10}}
									<li><span class="ipsType_light"><a href="{url="app=nexus&module=support&controller=requests&member={$request->member}"}" class="ipsType_blendLinks">{lang="and_x_others" pluralize="$otherRequests->count( TRUE ) - 10"}</a></span></li>
								{{endif}}
							</ul>
						</div>
					{{endif}}
					{{if member.hasAcpRestriction( 'nexus', 'payments', 'invoices_manage' ) and $invoices}}
						<div id="ipsTabs_elRequestMeta_elInvoiceHistory_panel" class="ipsTabs_panel ipsAreaBackground_reset ipsClearfix" aria-hidden="false">
							<ul>
								{{foreach $invoices as $invoice}}
									<li><a href="{$invoice->acpUrl()}">{$invoice->title}</a></li>
								{{endforeach}}
							</ul>
							{{if $invoices->count(TRUE) > 10}}
								<a href="{url="app=nexus&module=customers&controller=view&id={$request->member}&tab=invoices"}">{lang="and_x_others" pluralize="$invoices->count(TRUE) - 10"}</a>
							{{endif}}
						</div>
					{{endif}}
				</div>
			</div>
			
			{{if $request->member}}
				<div class="ipsBox ipsPad_half">
					<h2 class="ipsType_sectionHead ipsType_large">
						{lang="associated_purchase"}
					</h2>
					{{if $purchase = $request->purchase}}&nbsp;&nbsp;<a href="{$request->acpUrl()->setQueryString( 'do', 'associate' )}" data-ipsDialog data-ipsDialog-size='narrow' data-ipsDialog-title="{lang="associate"}" class="ipsType_small">({lang="change"})</a>{{endif}}
					{{if $purchase = $request->purchase}}
						<div class='cNexusSupportRequest_associated'>
							{expression="\IPS\nexus\Purchase::tree( $request->acpUrl(), array(), 's.' . $request->id, $purchase )" raw="true"}
						</div>
					{{else}}
						<div class="ipsType_center">
							<p class="{{if $request->department->require_package}}ipsType_warning ipsType_bold{{else}}ipsType_light{{endif}}" data-role="noPurchaseWarning">{lang="request_not_associated"}</strong></p>
							<a href="{$request->acpUrl()->setQueryString( 'do', 'associate' )}" data-ipsDialog data-ipsDialog-size='narrow' data-ipsDialog-title="{lang="associate"}" class="ipsButton ipsButton_alternate ipsButton_verySmall">{lang="associate"}</a><br>
							<br>
						</div>
					{{endif}}
				</div>
				<br>
			{{endif}}
			
			{{if $customFields = $request->department->customFields()}}
				{{$customFieldValues = $request->cfields;}}
				<div class="ipsBox ipsPad_half">
					<h2 class="ipsType_sectionHead ipsType_large">
						{lang="support_additional_info"}
					</h2>
					&nbsp;&nbsp;<a href="{$request->acpUrl()->setQueryString( 'do', 'cfields' )}" data-ipsDialog data-ipsDialog-title="{lang="custom_support_fields"}" class="ipsType_small">({lang="edit"})</a>
					<ul class='ipsList_reset ipsSpacer_top'>
						{{foreach $customFields as $field}}
							<li class='ipsSpacer_bottom ipsSpacer_half'>
								<h4 class='ipsType_minorHeading'>{$field->_title}</h4>
								<div class='ipsType_richText ipsType_medium ipsContained ipsType_break'>
									{{if isset( $customFieldValues[ $field->id ] ) and $customFieldValues[ $field->id ]}}
										{$field->displayValue( $customFieldValues[ $field->id ] )|raw}
									{{else}}
										<em class="ipsType_light">{lang="no_value"}</em>
									{{endif}}
								</div>
							</li>
						{{endforeach}}
					</ul>
				</div>
				<br>
			{{endif}}
			
			{{if $ppiInvoice = $request->ppi_invoice}}
				<div class="ipsBox ipsPad_half">
					<h2 class="ipsType_sectionHead ipsType_large">
						{lang="ppi_invoice"}
					</h2>
					&nbsp;&nbsp;<a href="{$ppiInvoice->acpUrl()}" class="ipsType_small">({lang="view"})</a>
					{{$summary = $ppiInvoice->summary();}}

					<ul class='ipsDataList ipsDataList_reducedSpacing ipsSpacer_top ipsSpacer_half ipsPad_half'>
						{{foreach $summary['items'] as $item}}
							{{if !( $item instanceof \IPS\nexus\extensions\nexus\Item\CouponDiscount )}}
								<li class='ipsDataItem'>
									<div class='ipsDataItem_main ipsType_break ipsContained'>
										<span class='ipsType_medium'>
											{{if $item->quantity > 1}}<span class='ipsType_light'>{$item->quantity} x </span>{{endif}}
											{$item->name}
										</span>
										{{if count( $item->details )}}
											<br>
											<span class="ipsType_light">
												{{foreach $item->details as $k => $v}}
													{lang="nexus_pfield_{$k}"}: {$v}<br>
												{{endforeach}}
											</span>
										{{endif}}
									</div>
									<div class='ipsDataItem_generic ipsDataItem_size3 ipsType_right'>
										<span class='cNexusPrice ipsType_normal'>{$item->linePrice()}</span>
										{{if $item->quantity > 1}}
											<p class='ipsType_reset ipsType_small ipsType_light'>{lang="each_short" sprintf="$item->price"}</p>
										{{endif}}
									</div>
								</li>
							{{endif}}
						{{endforeach}}
						{{foreach $summary['items'] as $item}}
							{{if $item instanceof \IPS\nexus\extensions\nexus\Item\CouponDiscount}}
								<li class='ipsDataItem cNexusCheckout_coupon'>
									<div class='ipsDataItem_main ipsType_right'>
										<strong>{lang="coupon"}</strong>
									</div>
									<div class='ipsDataItem_generic ipsDataItem_size3 ipsType_right cNexusPrice'>
										{$item->linePrice()}
									</div>
								</li>
							{{endif}}
						{{endforeach}}	
						<li class='ipsDataItem cNexusCheckout_subtotal'>
							<div class='ipsDataItem_main ipsType_right'>
								<strong>{lang="subtotal"}</strong>
							</div>
							<div class='ipsDataItem_generic ipsDataItem_size3 ipsType_right cNexusPrice'>
								{$summary['subtotal']}
							</div>
						</li>
						{{foreach $summary['tax'] as $tax}}
							<li class='ipsDataItem'>
								<div class='ipsDataItem_main ipsType_right'>
									<strong>{$tax['name']} <span class='ipsType_light ipsType_unbold'>({expression="$tax['rate']*100"}%)</span></strong>
								</div>
								<div class='ipsDataItem_generic ipsDataItem_size3 ipsType_right cNexusPrice'>
									{$tax['amount']}
								</div>
							</li>
						{{endforeach}}
						<li class='ipsDataItem ipsType_large cNexusCheckout_subtotal'>
							<div class='ipsDataItem_main ipsType_right'>
								<strong>{lang="total"}</strong>
							</div>
							<div class='ipsDataItem_generic ipsDataItem_size3 ipsType_right cNexusPrice'>
								<strong>{$summary['total']}</strong>
							</div>
						</li>
					</ul>
				</div>
				<br>
			{{endif}}
			
			<div class="ipsBox ipsPad_half">
				<h2 class="ipsType_sectionHead ipsType_large">
					{lang="viewed_by"}
				</h2>
				{{foreach $request->staffViews() as $view}}
					<div class='ipsPad_half ipsPhotoPanel ipsPhotoPanel_tiny ipsClearfix'>
						<img src='{member="photo" id="$view['view_member']"}' class='ipsUserPhoto ipsUserPhoto_tiny ipsPos_left'>
						<div>
							<strong>{member="name" id="$view['view_member']"}</strong>

							<ul class='ipsList_inline ipsType_small'>
								{{if $view['view_reply']}}
									<li><i class='fa fa-mail-reply'></i> {datetime="$view['view_reply']"}</li>
								{{endif}}
								<li {{if $view['view_last'] !== $view['view_first']}}data-ipsTooltip title="{lang="view_first"} {datetime="$view['view_first']" norelative="true"}"{{endif}}><i class='fa fa-eye'></i> {datetime="$view['view_last']"}</li>
							</ul>
						</div>
					</div>
				{{endforeach}}
			</div>
		</div>
	</div>
</div>