<ips:template parameters="$entry, $table" />

<article class='cBlogView_entry {{if $entry->hidden()}}ipsModerated{{endif}}'>
	<header class='ipsPhotoPanel ipsPhotoPanel_mini ipsPhotoPanel_notPhone'>
		{template="userPhoto" app="core" params="$entry->author(), 'mini'" group="global"}
		<div>
			<h2 class='ipsType_sectionHead ipsType_blendLinks ipsTruncate ipsTruncate_line'>
				{{if $entry->prefix()}}
					{template="prefix" group="global" app="core" params="$entry->prefix( TRUE ), $entry->prefix()"}
				{{endif}}
				<a href="{$entry->url()}" title="{lang="read_more_about" sprintf="$entry->name"}">
					{{if $entry->unread()}}
						<span class='ipsItemStatus' data-ipsTooltip title="{lang="unread_blog"}"><i class="fa fa-circle"></i></span>
					{{endif}}
					{wordbreak="$entry->name"}
				</a>
				{{if $entry->isFutureDate() || $entry->mapped('pinned') || $entry->mapped('featured') || $entry->hidden() === -1 || $entry->hidden() === 1}}
					{{if $entry->isFutureDate()}}
						<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_warning" data-ipsTooltip title='{$entry->futureDateBlurb()}'><i class='fa fa-clock-o'></i></span>
					{{elseif $entry->hidden() === 1}}
						<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_warning" data-ipsTooltip title='{lang="pending_approval"}'><i class='fa fa-warning'></i></span>
					{{endif}}
					{{if $entry->mapped('pinned')}}
						<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_positive" data-ipsTooltip title='{lang="pinned"}'><i class='fa fa-thumb-tack'></i></span>
					{{endif}}
					{{if $entry->mapped('featured')}}
						<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_positive" data-ipsTooltip title='{lang="featured"}'><i class='fa fa-star'></i></span>
					{{endif}}
				{{endif}}
			</h2>
			<p class='ipsType_light ipsType_reset'>
				{lang="byline" htmlsprintf="$entry->author()->link()"}{datetime="$entry->date"}
			</p>
			{{if \IPS\Settings::i()->blog_enable_rating}}
				{template="rating" app="core" params="'large', $entry->averageRating()" group="global"}
			{{endif}}	
		</div>
	</header>

	<section class='ipsType_normal ipsType_richText ipsType_break ipsSpacer_both' data-ipsTruncate data-ipsTruncate-size='4 lines' data-ipsTruncate-type='remove'>
		{$entry->truncated()|raw}
	</section>

	<ul class='ipsList_inline'>
		{{if $table->canModerate()}}
			<li class='ipsPos_left'>
				{{$idField = $entry::$databaseColumnId;}}
				<input type='checkbox' data-role='moderation' name="moderate[{$entry->$idField}]" data-actions="{expression="implode( ' ', $table->multimodActions( $entry ) )"}" data-state='{{if $entry->tableStates()}}{$entry->tableStates()}{{endif}}'>
			</li>
		{{endif}}
		<li><strong><a href='{$entry->url()}' title="{lang="read_more_about" sprintf="$entry->name"}">{lang="read_more"}</a></strong></li>
		<li><a href='{$entry->url()}#comments' title='{lang="view_comments"}'><i class='fa fa-comment'></i> {lang="num_comments" pluralize="$entry->num_comments"}</a></li>
		<li class='ipsType_light'>{lang="num_views_with_number" pluralize="$entry->views"}</li>
	</ul>		
</article>