<ips:template parameters="$image, $slider, $next=NULL, $prev=NULL, $hasNext=TRUE, $hasPrev=TRUE" />

<div data-controller='gallery.front.view.image'>
	<div id='elGalleryHeader'>
		{template="imageFrame" group="view" app="gallery" params="$image, $slider, $next, $prev"}
		<div id='elGalleryNav' data-role='collectionNav'>
			<ul class='ipsList_inline ipsClearfix'>
				{template="imageSlider" group="view" app="gallery" params="$image, $slider, $next, $prev, $hasNext, $hasPrev"}
			</ul>
			<p class='ipsType_reset ipsType_center'>
				{lang="slider_text" pluralize="$image->directContainer()->count_imgs" sprintf="$image->directContainer()->_title"}
			</p>
		</div>
	</div>

	<section data-role='imageInfo'>
		{template="imageInfo" group="view" params="$image, $slider, $next, $prev"}	
	</section>

	<div data-role='imageComments'>
		{{if $image->directContainer()->allow_comments}}
			{template="comments" app="gallery" group="view" params="$image"}
		{{endif}}
	</div>
</div> 