<ips:template parameters="$request, $id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class='', $attributes=array(), $sidebar, $form=NULL" />

<form accept-charset='utf-8' class="cNexusSupportForm cNexusSupportForm_note ipsComposeArea ipsForm {$class}" action="{$action}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}} {{foreach $attributes as $k => $v}}{$k}="{$v}"{{endforeach}} data-ipsForm id='elNoteForm'>
	<input type="hidden" name="{$id}_submitted" value="1">
	{{foreach $hiddenValues as $k => $v}}
		{{if is_array($v)}}
			{{foreach $v as $_k => $_v}}
				<input type="hidden" name="{$k}[{$_k}]" value="{$_v}">
			{{endforeach}}
		{{else}}
			<input type="hidden" name="{$k}" value="{$v}">
		{{endif}}
	{{endforeach}}
	{{if $uploadField}}
		<input type="hidden" name="MAX_FILE_SIZE" value="{$uploadField}">
		<input type="hidden" name="plupload" value="{expression="md5( uniqid() )"}">
	{{endif}}

	{{if $elements['']['note']}}
		<div class='cNexusSupportForm_message'>
			{$elements['']['note']->html()|raw}
		</div>
	{{endif}}

	<div class='ipsAreaBackground ipsClearfix ipsPad_half ipsType_right' data-ipsEditor-toolList>
		<ul class='ipsList_inline ipsPos_left ipsType_left cNexusSupportForm_controls'>
			{{if isset( $elements['']['status'] )}}
				<li>
					<h3 class='ipsType_minorHeading'>{lang="status"}</h3>
					{$elements['']['status']->html()|raw}
				</li>
			{{endif}}
			{{if isset( $elements['']['department'] )}}
				<li>
					<h3 class='ipsType_minorHeading'>{lang="department"}</h3>
					{$elements['']['department']->html()|raw}
				</li>
			{{endif}}
			{{if isset( $elements['']['assign_to'] )}}
				<li>
					<h3 class='ipsType_minorHeading'>{lang="assign_to"}</h3>
					{$elements['']['assign_to']->html()|raw}
				</li>
			{{endif}}
		</ul>
		{{$next = $request->nextPrevious( \IPS\Request::i()->sort, \IPS\Request::i()->filter );}}
		<ul class='ipsButton_split ipsType_noBreak ipsPos_right cNexusSupportForm_buttons'>
			<li><button type='submit' class='ipsButton ipsButton_primary ipsButton_large' name='goto' {{if $next}}value='next'{{else}}value='list'{{endif}}>{lang="add_note"}</button></li>
			<li>
				<a href='#' class='ipsButton ipsButton_primary ipsButton_large ipsButton_narrow' id='elNoteForm_more' data-ipsMenu data-ipsMenu-appendTo='#elNoteForm'>
					<i class='fa fa-caret-down'></i>
				</a>
				<ul id='elNoteForm_more_menu' class='ipsMenu ipsMenu_narrow ipsHide'>
					<li class='ipsMenu_item ipsPad_half'><button type='submit' class='ipsButton ipsButton_primary ipsButton_small ipsButton_fullWidth'>{lang="note_and_stay"}</button></li>
					{{if $next}}
						<li class='ipsMenu_item ipsPad_half'><button type='submit' class='ipsButton ipsButton_primary ipsButton_small ipsButton_fullWidth' name='goto' value='list'>{lang="note_and_go_to_list"}</button></li>
					{{endif}}
				</ul>
			</li>
		</ul>
	</div>
</form>