<ips:template parameters="$album" />

<ol class='ipsGrid ipsList_reset cGalleryMiniAlbum ipsClearfix' data-ipsGrid data-ipsGrid-minItemSize='60' data-ipsGrid-maxItemSize='100'>
	{{foreach $album->_latestImages as $image}}
		{{if $image->media}}
			<li class='ipsGrid_span3 ipsNoThumb ipsNoThumb_video'>&nbsp;</li>
		{{else}}
			<li style='background-image: url( {$image->small_file_name} );' class='ipsGrid_span3 cGalleryTrimmedImage' data-grid-ratio='100' data-imageID='{$image->id}'>
				<a href='{$image->url()->setQueryString( 'browse', 1 )}' title='{$image->caption}' data-ipsLightbox data-ipsLightbox-group='g{$album->id}' data-fullURL="{$image->masked_file_name}">
					<img src='{$image->small_file_name}' alt='{$image->caption}'>
				</a>
			</li>
		{{endif}}
	{{endforeach}}
</ol>
<a href='{$album->url()}' class='ipsType_small'>{lang="view_entire_album" sprintf="$album->name"}</a>