<ips:template parameters="$latestImage, $orientation='vertical'" />
<div id='elGalleryStatsLatest' class='ipsClearfix cGalleryWidget'>
	<strong class='ipsType_minorHeading'>{lang="latest_image"}</strong><br>
	<div class='ipsType_center'>
		<a href='{$latestImage->url()}' title='{lang="view_this_image" sprintf="$latestImage->caption"}'>
			{{if $latestImage->medium_file_name}}
				<img src='{$latestImage->medium_file_name}' alt='' class='ipsImage'>
			{{else}}
				<div class='ipsImage ipsNoThumb ipsNoThumb_video'>&nbsp;</div>
			{{endif}}
		</a>
	</div>
	<div>
		{{if $latestImage->directContainer()->allow_comments}}
			<div class="ipsCommentCount ipsPos_right {{if $latestImage->comments === 0}}ipsFaded{{endif}}" data-ipsTooltip title='{lang="num_comments" pluralize="$latestImage->comments"}'>
				{$latestImage->comments}
			</div>
		{{endif}}
		{{if $latestImage->unread()}}<span class="ipsItemStatus ipsItemStatus_small"><i class="fa fa-circle"></i></span> <strong>{{endif}}<a href="{$latestImage->url()}" title='{lang="view_this_image" sprintf="$latestImage->caption"}'>{wordbreak="$latestImage->caption"}</a>{{if $latestImage->unread()}}</strong>{{endif}}<br>
		<span class='ipsType_light ipsType_small'>{lang="byline_nodate" htmlsprintf="$latestImage->author()->link()"} &middot; {datetime="$latestImage->mapped('date')" norelative="true"}</span><br>
	</div>
</div>