<ips:template parameters="$image, $highlight=FALSE, $json=FALSE" />
{{if $image}}
	{{if $image->media}}
		<li class='ipsNoThumb ipsNoThumb_video ipsCursor_pointer' data-imageID='{$image->id}'>
			<a href='{$image->url()->setQueryString( 'browse', 1 )}' title='{$image->caption}'></a>
		</li>
	{{else}}
		<li style='background-image: url( {$image->thumb_file_name} );' class='cGalleryTrimmedImage {{if $highlight}}cGalleryAlbumSlider_active{{endif}}' data-imageID='{$image->id}'>
			<a href='{$image->url()->setQueryString( 'browse', 1 )}' title='{$image->caption}'>
				<img src='{$image->thumb_file_name}' alt='{$image->caption}'>
			</a>
		</li>
	{{endif}}
{{else}}
	<li class='ipsAreaBackground'>&nbsp;</li>
{{endif}}