<ips:template parameters="$file, $orientation='vertical'" />
<li class='ipsDataItem {{if $orientation == 'horizontal'}}ipsGrid_span3{{endif}}'>
	<div class='ipsDataItem_icon ipsPos_top'>
		{template="thumbImage" group="global" app="core" params="$file->primary_screenshot, $file->name, 'tiny'"}
		{{$price = NULL;}}
		{{if \IPS\Application::appIsEnabled( 'nexus' ) and settings.idm_nexus_on}}
			<p class="cFilePrice ipsType_reset ipsType_medium ipsType_center">
				{{if $price = $file->price()}}
					{$price|raw}
				{{else}}
					{lang="file_free"}
				{{endif}}
			</p>
		{{endif}}
	</div>
	<div class='ipsDataItem_main ipsType_break'>
		<a href="{$file->url()}" title='{lang="view_this_file" sprintf="$file->name"}'>{wordbreak="$file->name"}</a>
		<br>
		<span class='ipsType_light ipsType_medium'>{lang="byline_nodate" htmlsprintf="$file->author()->link()"}</span><br>
		{{if $file->container()->bitoptions['reviews']}}
			{template="rating" group="global" location="front" app="core" params="'small', $file->rating, \IPS\Settings::i()->reviews_rating_out_of"} &nbsp;&nbsp;
		{{endif}}

		<span class='ipsType_medium ipsType_reset ipsType_noBreak'>
			{{if $file->price() and in_array( 'purchases', explode( ',', settings.idm_nexus_display ) )}}
				<span {{if !$file->purchaseCount()}}class='ipsType_light'{{endif}} title='{lang="idm_purchases"}' data-ipsTooltip><i class='fa fa-shopping-cart'></i> {$file->purchaseCount()}</span>&nbsp;&nbsp;
			{{endif}}
			{{if !$file->price() or in_array( 'downloads', explode( ',', settings.idm_nexus_display ) )}}
				<span {{if !$file->downloads}}class='ipsType_light'{{endif}} title='{lang="downloads"}' data-ipsTooltip><i class='fa fa-arrow-circle-down'></i> {$file->downloads}</span>&nbsp;&nbsp;
			{{endif}}

			{{if $file->container()->bitoptions['comments']}}<span {{if !$file->comments}}class='ipsType_light'{{endif}} title='{lang="total_comments"}' data-ipsTooltip><i class='fa fa-comment'></i> {$file->comments}{{endif}}
		</span>
	</div>
</li>