<ips:template parameters="$file" />
<div class='ipsAreaBackground_reset ipsType_blendLinks ipsClearfix cDownloadsCarouselItem ipsPad_half ipsCarousel_item'>
	<a href='{$file->url()}' title='{lang="view_this" sprintf="$file->name"}'>
		{template="thumbImage" group="global" app="core" params="$file->primary_screenshot_thumb, $file->name"}
    </a>
		<div class='cDownloadsCarouselItem_info ipsSpacer_top ipsSpacer_half'>
			<h3 class='ipsType_normal ipsType_reset ipsTruncate ipsTruncate_line'>
				{{if $file->unread()}}
					<span class='ipsItemStatus ipsItemStatus_small' data-ipsTooltip title='{{if $file->unread() === -1}}{lang="new"}{{else}}{lang="updated"}{{endif}}'><i class="fa fa-circle"></i></span>&nbsp;
				{{endif}}
                <a href='{$file->url()}' title='{lang="view_this" sprintf="$file->name"}'>{$file->name}</a>
			</h3>
			
			<p class='ipsType_medium ipsType_reset ipsType_blendLinks ipsTruncate ipsTruncate_line'>{lang="byline_nodate" htmlsprintf="$file->author()->link()"}</p>
			{{if $file->container()->bitoptions['reviews']}}
				{template="rating" group="global" location="front" app="core" params="'medium', $file->rating, \IPS\Settings::i()->reviews_rating_out_of"}
			{{endif}}
			<p class='ipsType_medium ipsType_reset'>
				{{if $price = $file->price() and in_array( 'purchases', explode( ',', settings.idm_nexus_display ) )}}
					<span {{if !$file->purchaseCount()}}class='ipsType_light'{{endif}} title='{lang="idm_purchases"}' data-ipsTooltip><i class='fa fa-shopping-cart'></i> {$file->purchaseCount()}</span>&nbsp;&nbsp;
				{{endif}}
				{{if !$file->price() or in_array( 'downloads', explode( ',', settings.idm_nexus_display ) )}}
					<span {{if !$file->downloads}}class='ipsType_light'{{endif}} title='{lang="downloads"}' data-ipsTooltip><i class='fa fa-arrow-circle-down'></i> {$file->downloads}</span>&nbsp;&nbsp;
				{{endif}}
				 
				{{if $file->container()->bitoptions['comments']}}<span {{if !$file->comments}}class='ipsType_light'{{endif}} title='{lang="total_comments"}' data-ipsTooltip><i class='fa fa-comment'></i> {$file->comments}{{endif}}
			</p>
			
			{{if \IPS\Application::appIsEnabled( 'nexus' ) and settings.idm_nexus_on}}
				<span class="cFilePrice ipsType_medium">
					{{if $price = $file->price()}}
						{$price|raw}
					{{else}}
						{lang="file_free"}
					{{endif}}
				</span>
			{{endif}}
		</div>
</div>