<ips:template parameters="$table, $headers, $rows" />
{{$currentTimestamp = null;}}
{{foreach $rows as $row}}
	{{if $currentTimestamp != $row['log_date']->format('n') . '|' . $row['log_date']->format('Y')}}
		<li class='cCustomerHistory_date'>
			{$row['log_date']->format('F')} {$row['log_date']->format('Y')}
		</li>
		{{$currentTimestamp = $row['log_date']->format('n') . '|' . $row['log_date']->format('Y');}}
	{{endif}}
	<li class='ipsClearfix'>
		<div class='cCustomerHistory_icon ipsPos_left'>
			{$row['log_type']|raw}
		</div>
		<div class='cCustomerHistory_info ipsType_normal'>
			{$row['log_data']|raw}
			<br>
			<span class='ipsType_medium ipsType_light'>{$row['log_date']->relative()|raw}</span>
		</div>
	</li>
{{endforeach}}