<ips:template parameters="$invoice, $summary" />

{setting="nexus_invoice_header"}
<table style="font-family: 'helvetica', 'arial', 'verdana', sans-serif">
	<tr>
		<td style="width: 70%">
			<h1>{lang="invoice_number" sprintf="$invoice->id"}</h1>
			<br>
			{{if $invoice->po}}
				{lang="invoice_po_number"}: {$invoice->po}<br>
				<br>
			{{endif}}
			{$invoice->member->cm_name}<br>
			{{if $invoice->billaddress}}{$invoice->billaddress->toString('<br>')|raw}{{endif}}
		</td>
		<td>
			<strong>{setting="board_name"}</strong><br>
			{expression="\IPS\GeoLocation::buildFromJson( \IPS\Settings::i()->site_address )->toString('<br>')" raw="true"}<br>
			<br>
			{$invoice->date->format( 'd F Y' )}
		</td>
	</tr>
</table>
<br style="clear:both">
{{if $invoice->notes}}
	<div style="font-family: 'helvetica', 'arial', 'verdana', 'sans-serif'">{$invoice->notes}</div>
{{endif}}
<br>
<table border="1" style="padding: 5px; font-family: 'helvetica', 'arial', 'verdana', sans-serif">
	<thead>
		<tr style="background-color:black; color:white">
			<th>{lang="invoice_item"}</th>
			<th>{lang="invoice_unit_price"}</th>
			<th>{lang="invoice_quantity"}</th>
			<th>{lang="invoice_line_price"}</th>
		</tr>
	</thead>
	<tbody>
		{{foreach $summary['items'] as $k => $item}}
			<tr>
				<td>{$item->name}</td>
				<td>{$item->price}</td>
				<td>{$item->quantity}</td>
				<td>{$item->linePrice()}</td>
			</tr>
		{{endforeach}}
	</tbody>
</table>
<br>
<table style="padding: 5px; font-family: 'helvetica', 'arial', 'verdana', sans-serif">
	<tfoot>
		<tr>
			<td colspan="3" style="text-align:right"><strong>{lang="subtotal"}</strong></td>
			<td><strong>{$summary['subtotal']}</strong></td>
		</tr>
		{{foreach $summary['shipping'] as $shipping}}
			<tr>
				<td colspan="3" style="text-align:right">{$shipping->name}</td>
				<td>{$shipping->linePrice()}</td>
			</tr>
		{{endforeach}}
		{{foreach $summary['tax'] as $tax}}
			<tr>
				<td colspan="3" style="text-align:right">{$tax['name']} ({expression="$tax['rate']*100"}%)</td>
				<td>{$tax['amount']}</td>
			</tr>
		{{endforeach}}
		<tr>
			<td colspan="3" style="text-align:right; font-size: 1.5em"><strong>{lang="total"}</strong></td>
			<td><strong style="font-size: 1.5em">{$summary['total']}</strong></td>
		</tr>
	</tfoot>
</table>
{setting="nexus_invoice_footer"}