<ips:template parameters="$title,$html,$location=array()" />
<!DOCTYPE html>
<html lang="{expression="\IPS\Member::loggedIn()->language()->bcp47()"}" dir="{{if member.language()->isrtl}}rtl{{else}}ltr{{endif}}">
	<head>
		<title>{expression="output.getTitle( $title )"}</title>
		<!--[if lt IE 9]>
			{{foreach \IPS\Theme::i()->css( 'extra/ie8.css', 'core' ) as $css}}<link rel="stylesheet" type="text/css" href="{$css}">{{endforeach}}
		    <script src="{url="applications/core/interface/html5shiv/html5shiv.js" base="none"}"></script>
		<![endif]-->

		<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,300' rel='stylesheet' type='text/css'>
		<link rel='stylesheet' id='admin-bar-css' href='http://www.soompi.com/wp-includes/css/admin-bar.min.css?ver=3.9.2' type='text/css' media='all'/>
		<link rel='stylesheet' id='compiled-sitewide-css' href='http://www.soompi.com/wp-content/static/1/css/sitewide.1429563319.css' type='text/css' media='all'/>

		{template="includeMeta" app="core" group="global" location="global" params=""}
		{template="includeCSS" app="core" group="global" location="global" params=""}
		{template="includeJS" if="theme.js_include != 'footer'" app="core" group="global" location="global" params=""}
		{template="favico" app="core" group="global" location="front" params=""}

	</head>
	<body class='ipsApp ipsApp_front ipsJS_none ipsClearfix{{foreach output.bodyClasses as $class}} {$class}{{endforeach}}' {{if output.globalControllers}}data-controller='{expression="implode( ',', output.globalControllers )"}'{{endif}} {{if isset( output.inlineMessage )}}data-message="{expression="output.inlineMessage"}"{{endif}} data-pageApp='{$location['app']}' data-pageLocation='front' data-pageModule='{$location['module']}' data-pageController='{$location['controller']}' itemscope itemtype="http://schema.org/WebSite">
		<meta itemprop="url" content="{url="/"}">
		<a href='#elContent' class='ipsHide' title='{lang="jump_to_content_desc"}' accesskey='m'>{lang="jump_to_content"}</a>
		{template="offlineMessage" if="!settings.site_online && \IPS\Member::loggedIn()->group['g_access_offline']" app="core" group="global" params=""}

		<div id="wpadminbar" class="nojq nojs" role="navigation">
		   <div class="quicklinks">
		      <ul id="wp-admin-bar-root-default" class="ab-top-menu">
		         <li id="wp-admin-bar-network-star" class="menupop">
		            <a class="ab-item" tabindex="10" aria-haspopup="true" href="http://www.soompi.com">
		               <span class="icon star">Soompi</span>
		            </a>
		         </li>
		         <li class="network-site">
		            <a class="ab-item" tabindex="10" href="http://www.soompi.com">News</a>     
		         </li>
		         <li class="network-site current-network-site">
		            <a class="ab-item" href="http://forums.soompi.com">Forums</a>
		            <span class="sep"></span>
		         </li>
		         <li class="network-site">
		            <a class="ab-item" href="http://shop.soompi.com/">Shop</a>
		            <span class="sep"></span>
		         </li>
		         <li class="network-site">
		            <a class="ab-item" href="http://tv.soompi.com/en/home?from=global-nav-forum">SoompiTV <span class="nav-new">NEW!</span></a>
		            <span class="sep"></span>
		         </li>
		      </ul>
		      <ul id="wp-admin-bar-top-secondary" class="ab-top-secondary ab-top-menu">
        
              </ul>
		   </div>
		</div>
		{{if !in_array('ipsLayout_minimal', \IPS\Output::i()->bodyClasses )}}{template="userBar" app="core" group="global" params=""}{{endif}} 
		<div id='ipsLayout_header' class='ipsClearfix'>
			{template="lkeyWarning" app="core" group="global" location="global" params=""}
			{{if !in_array('ipsLayout_minimal', \IPS\Output::i()->bodyClasses )}}{template="mobileNavBar" app="core" group="global" params=""}{{endif}}
			<header>
				<div class='ipsLayout_container'>
					{template="logo" app="core" group="global" params=""}
				</div>
				<div class="site-header ipsLayout_container">
				<nav id="access" role="navigation">
					<div class="assistive-text section-heading">Main menu</div>
					<div class="skip-link screen-reader-text">
						<a class="assistive-text" href="#realm-content" title="Skip to content">
					Skip to content </a>
					</div>
					<ul id="site-nav-menu" class="menu">
						<li id="menu-item-532967" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-532967"><a href="http://www.soompi.com/">Home</a></li>
						<li id="menu-item-soompitv" class="menu-item menu-item-type-custom menu-item-object-custom" title="Watch SoompiTV"><a href="http://tv.soompi.com/en/home?from=main-nav-wp" style="width:110px;"><span class="nav-tv"></span></a></li>
						<li id="menu-item-377702" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-377702"><a href="/news/">News</a></li>
						<li id="menu-item-377703" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-377703"><a href="/gallery/">Gallery</a></li>
						<li id="menu-item-530855" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-530855"><a href="http://www.soompi.com/tag/soompi-exclusive/">Exclusives</a></li>
						<li id="menu-item-377708" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-377708 current-menu-item"><a href="http://forums.soompi.com/sso/">Forums</a></li>
						<li id="menu-item-430032" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-430032"><a href="https://shop.soompi.com/">Shop</a></li>
						<li style="display:none;" id="menu-item-mobile" class="menu-item menu-item-type-custom menu-item-object-custom" title="login"><a href="http://tv.soompi.com/en/login?return_to=http%3A%2F%2Fwww.soompi.com%2F">login</a></li>
					</ul>
					<div id="header-language-network">
						<h6 class="menu-label">LANGUAGE</h6>
						<ul id="menu-language-bar-navigation" class="menu">
							<li id="menu-item-377710" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-377710"><a href="http://www.soompi.com/fr/">Français</a><span class="sep"></span></li>
							<li id="menu-item-377709" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-377709"><a href="http://www.soompi.com/es/">Español</a><span class="sep"></span></li>
						</ul> 
					</div>
				</nav>
				</div> 
			</header>
			{template="navBar" app="core" group="global" params=""}
		</div>
		<main role='main' id='ipsLayout_body' class='ipsLayout_container'>
			<div id='ipsLayout_contentArea'>
				<div id='elHeaderNavigation' class='ipsSubNavigation'>
					{template="utilitiesMenu" app="core" group="global" params=""}
					{template="breadcrumb" app="core" group="global" params="true"}
				</div>
				<div id='ipsLayout_contentWrapper'>
					{template="sidebar" if="theme.sidebar_position == 'left'" app="core" group="global" params="'left'"}
					<div id='ipsLayout_mainArea'>
						<a id='elContent'></a>
						{advertisement="ad_global_header"}
						{template="acknowledgeWarning" if="\IPS\Member::loggedIn()->members_bitoptions['unacknowledged_warnings']" params="\IPS\Member::loggedIn()->warnings( 1, FALSE )" group="global" app="core"}
						{template="widgetContainer" group="global" app="core" params="'header', 'horizontal'"}
						{$html|raw}
						{template="widgetContainer" group="global" app="core" params="'footer', 'horizontal'"}
						{advertisement="ad_global_footer"}
					</div>
					{template="sidebar" if="theme.sidebar_position == 'right'" app="core" group="global" params="'right'"}
				</div>
				<div id='elFooterNavigation' class='ipsSubNavigation'>
					{template="rssMenu" app="core" group="global" params=""}
					{template="breadcrumb" app="core" group="global" params="false"}
				</div>
			</div>
			{template="inlineMessage" if="member.msg_show_notification and $conversation = \IPS\core\Messenger\Conversation::latestUnreadConversation()" app="core" group="global" params="$conversation->comments( 1, NULL, 'date', 'desc' )"}
		</main>
		<footer id='ipsLayout_footer' class='ipsClearfix'>
			<div class='ipsLayout_container'>
				{template="footer" app="core" group="global" params=""}
			</div>
		</footer>

		<!-- Begin Soompi Footer -->
		<footer id="site-footer" role="contentinfo">
		   <div class="inner">
		      <div id="footer-network-bar" class="top columns-3">
		        <div class="page-center">
		          <div id="footer-network-links">
		            <div class="network-star">
		               <a href="/">
		                  <span class="star"></span>
		               </a>
		            </div>

		            <ul id="menu-network-bar-navigation" class="menu">
		               <li id="menu-item-750" class="menu-item current-menu-item">
		                  <a href="http://www.soompi.com">News</a>
		                  <span class="sep"></span>
		               </li>
		               <li class="menu-item">
		                  <a href="http://forums.soompi.com">Forums</a>
		                  <span class="sep"></span>
		               </li>
		               <li class="menu-item">
		                  <a href="http://shop.soompi.com/">Shop</a>
		                  <span class="sep"></span>
		               </li>
		               <li class="network-site">
		                  <a class="ab-item" href="http://tv.soompi.com/en/home?from=global-nav-forum">SoompiTV <span class="nav-new">NEW!</span></a>
		                  <span class="sep"></span>
		               </li>
		            </ul>
		          </div>

		          <div id="footer-language-network">
		            <h6 class="menu-label">Need a different language?</h6>
		            <ul id="menu-language-bar-navigation" class="menu">
		                            <li id="menu-item-748" class="menu-item">
		                <a href="http://forums.soompi.fr/">Français</a><span class="sep"></span>
		              </li>
		                                          <li id="menu-item-749" class="menu-item">
		                <a href="http://forums.soompi.es/">Español</a><span class="sep"></span>
		              </li>
		                                        </ul> 
		          </div>

		          <!-- Social -->
		          <div id="footer-social">
		             <h6 class="menu-label">FOLLOW US</h6>
		             <ul class="menu">
		                <li class="fb-link">
		                   <a class="icon fb" title="Follow Soompi on Facebook" href="http://facebook.com/soompi">Facebook</a>
		                </li>
		                <li class="twitter-link">
		                   <a class="icon twitter" title="Follow Soompi on Twitter" href="http://twitter.com/soompi">Twitter</a>
		                </li>
		                <li class="gplus-link">
		                   <a class="icon gplus" title="Follow Soompi on Google Plus" href="https://plus.google.com/+SoompiKpop">Google Plus</a>
		                </li>
		             </ul>
		          </div>
		        </div><!-- /.page-center -->
		      </div><!-- #footer-network-bar -->

		      <div class="bottom">
		        <div class="page-center">
		          <div id="bottom-banner-region" role="complementary">
		            <div class="widget ad-placement">
		  <div class="ad-block ">
		    <div id="soompi-bottom-banner-ad" class="ad" style="width:728px;height:90px;">
					<span class="ad-unit-name" style="display:none;">Soompi_Forums_Leaderboard_BTF</span>
					<span class="mobile-ad-unit-name" style="display:none;"></span>       
		    </div>
		  </div>
		</div>
		          </div>
		          <div id="corporate">
		            <ul id="corporate-links" class="menu">
		              <li id="menu-item-386703" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-386703">
		                <a href="http://www.soompi.com/about/">About us</a>
		              </li>
		              <li id="menu-item-386695" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-386695">
		                <a href="http://www.soompi.com/terms/">Terms of service</a>
		              </li>
		              <li id="menu-item-386694" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-386694">
		                <a href="http://www.soompi.com/privacy/">Privacy Policy</a>
		              </li>
		              <li id="menu-item-386704" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-386704">
		                <a href="mailto:ads@soompi.com">Advertising info</a>
		              </li>
		              <li id="menu-item-386705" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-386705">
		                <a href="mailto:info@soompi.com">Contact us</a>
		              </li>
		            </ul>
		            <span id="copyright">&copy; 2014 Soompi Inc.</span>
		          </div>
		        </div><!-- .page-center -->
		      </div><!-- .bottom -->

		   </div><!-- /.inner -->
		</footer>

		{{if !in_array('ipsLayout_minimal', \IPS\Output::i()->bodyClasses )}}{template="mobileNavigation" if="theme.responsive" app="core" group="global" params=""}{{endif}}
		{template="includeJS" if="theme.js_include == 'footer'" app="core" group="global" location="global" params=""}
		{{if settings.ipbseo_ga_enabled}}
			{setting="ipseo_ga"}
		{{endif}}
		{template="viglink" if="settings.viglink_enabled" app="core" group="global" params=""}
		{template="metaTagEditor" if="isset( $_SESSION['live_meta_tags'] ) and $_SESSION['live_meta_tags'] and member.isAdmin()" app="core" group="global" params=""}
		<!--ipsQueryLog-->
		<!--ipsCachingLog-->
		{expression="output.endBodyCode" raw="true"}
	</body>
</html>