<ips:template parameters="$rootId, $purchases, $halfSize=FALSE" />
{{foreach $purchases[$rootId] as $purchase}}
	<li class='ipsSpacer_bottom ipsSpacer_double cNexusPurchaseList'>
		<div class='ipsBox ipsBox_transparent'>
			<div class='ipsPad{{if $halfSize}}_half{{endif}} ipsAreaBackground ipsPhotoPanel ipsPhotoPanel_mini'>
				<p class='ipsPos_right ipsType_reset ipsPad_half'>
					{{if $purchase->canRenewUntil(NULL,TRUE)}}
						<strong>{lang="purchases_renewal_price"} {money="$purchase->renewal_price"}</strong> &nbsp;&nbsp;<a href="{$purchase->url()->setQueryString( 'do', 'renew' )->csrf()}" class='ipsButton ipsButton_veryLight ipsButton_verySmall cNexusPurchaseList_button' title="{lang="purchase_renew_now_title"}">{lang="purchase_renew_now"}</a>
					{{endif}}
					<a href='{$purchase->url()}' class='ipsButton ipsButton_primary ipsButton_verySmall cNexusPurchaseList_button' title="{lang="purchases_manage_purchase"}">{lang="manage"}</a>
				</p>
				{{if $image = $purchase->image()}}
					<a href='{$purchase->url()}' class='ipsPos_left cNexusPurchaseList_image' style='background-image: url( {$image} );' title="{lang="purchases_manage_purchase"}">&nbsp;</a>
				{{else}}
					<a href='{$purchase->url()}' class='ipsPos_left ipsPos_left ipsNoThumb ipsNoThumb_product' title="{lang="purchases_manage_purchase"}">&nbsp;</a>
				{{endif}}
				<div>
					<h2 class='ipsType_sectionHead ipsType_blendLinks'><a href="{$purchase->url()}" title="{lang="purchases_manage_purchase"}">{$purchase->name}</a></h2>
					<p class='ipsType_reset ipsType_medium'>{lang="$purchase->getTypeTitle()"}</p>
				</div>
			</div>
			<div class='ipsPad{{if $halfSize}}_half{{endif}} cNexusPurchaseList_info ipsAreaBackground_light'>
		
				{{if $pendingInvoice = $purchase->invoice_pending}}
					<p class='ipsType_normal ipsType_reset'>
						<i class='fa fa-info-circle'></i> {lang="purchase_pending_invoice"} {{if $pendingInvoice}}<a href="{$pendingInvoice->checkoutUrl()}" title="{lang="order_pay_now_title"}">{lang="order_pay_now"}</a>{{endif}}
					</p>
					<hr class='ipsHr'>
				{{endif}}
		
				<div class='ipsGrid ipsGrid_collapsePhone'>
					<div class='ipsGrid_span3'>
						<h3 class='ipsType_minorHeading'>{lang="purchase_status"}</h3>
						<span class='ipsType_normal'>{{if $purchase->active}}<span class='ipsBadge ipsBadge_positive'>{lang="purchase_active"}</span>{{elseif $purchase->cancelled}}<span class='ipsBadge ipsBadge_negative'>{lang="purchase_canceled"}</span>{{else}}<span class='ipsBadge ipsBadge_neutral'>{lang="purchase_expired"}</span>{{endif}}</span>
					</div>
					<div class='ipsGrid_span3'>
						<h3 class='ipsType_minorHeading'>{lang="ps_start"}</h3>
						<span class='ipsType_normal'>{$purchase->start->localeDate()}</span>
					</div>
					{{if $purchase->expire}}
						<div class='ipsGrid_span3'>
							<h3 class='ipsType_minorHeading'>{lang="ps_expire"}</h3>
							<span class='ipsType_normal'>{$purchase->expire->localeDate()}</span>
						</div>
					{{endif}}
				</div>
			</div>
		</div>
		{{if isset( $purchases[ $purchase->id ])}}
			<ul class='ipsList_reset cNexusPurchaseSubList'>
				{template="purchaseList" group="clients" params="$purchase->id, $purchases, TRUE"}
			</ul>
		{{endif}}
	</li>
{{endforeach}}